### ISSUE TITLE
报错Uncaught TypeError: Cannot read properties of undefined (reading 'each')

### ISSUE THREAD

**Issue by Leslie622** [viryaka/98BAMI#1]
在https://www.sehuatang.net/forum*页面，selector1为什么undefined，search页面则是正常的

**Comment by Leslie622** [comment]
找到问题了，比如https://www.sehuatang.net/forum-95-1这种，匹配不上，我自己加上了

**Comment by Leslie622** [comment]
额，好像还是匹配不上

**Comment by viryaka** [comment]
> 额，好像还是匹配不上

多谢反馈，因为登录和非登录状态网址结构不一样

已修复，请更新3.5.6
